---

- hosts: localhost
  become: true
  roles:
      - common 

  vars_prompt:

    - name: username
      prompt: What is your username?
      private: no
      default: bruno
      
      #- name: password
      #prompt: What's your password?
      #unsafe: yes
      #private: yes

    - name: desktop_environment
      prompt: |-
        Which Desktop Environent do you want to install?
        (multiple options possible (e.g 1,2 for KDE && XFCE), press RET for headless install)
          1- KDE
          2- XFCE
          3- i3/PolyBar
      private: no

    - name: is_vm
      prompt: Is this a virtual machine? (y/N)
        private: no
        default: N
