---

- hosts: localhost
  become: true
  roles:
      - common 

  vars_prompt:

    - name: username
      prompt: What is your username?
      private: no
      default: bruno
      
    - name: password
      prompt: What's your password?
      unsafe: yes
      private: yes

    - name: display_manager
      prompt: |-
        Which display manager? (only one is allowed)
          1- Ly (Console DM)
          2- LightDM (light graphical DM)
          3- SDDM (successor of KDM)
      private: no
     
    - name: desktop_environment
      prompt: |-
        Which Desktop Environent do you want to install?
        (multiple options possible (e.g 1,2 for KDE && XFCE))
          1- KDE
          2- XFCE
      private: no
