- name: Create AUR directory
  file: path=/home/{{ username }}/{{ aur.dir }}
        state=directory
        owner={{ username }}
        group={{ username }}

- name: Install AUR base packages
  become: yes
  become_user: "{{ username }}"
  kewlfft.aur.aur:
    name: "{{ aur.packages }}"
    use: makepkg

- name: Install rcm
  become: yes
  become_user: "{{ username }}"
  kewlfft.aur.aur: name=rcm use=makepkg 

- name: Instal micro editor
  become: yes
  become_user: "{{ username }}"
  kewlfft.aur.aur: name=micro-git use=makepkg
