- name: install basic utils, shells, apps
  community.general.pacman:
   name:
    - xorg
    - xorg-xinit
    - kitty
    - vlc
    - gimp
    - git
    - thefuck
    - tmux
    - lsd
    - vim
    - source-highlight
    - tree
    - base-devel
   state: present

- name: install ranger
  community.general.pacman:
    name:
      - python-pillow
      - highlight
      - ranger

- name: Install archival utils
  pacman:
    name:
      - atool
      - p7zip
      - unrar
      - unzip
      - xz
      - zip
      - bzip2
      - gzip
      - tar
    state: present

- name: Install download utils
  pacman:
    name:
      - aria2
      - curl
      - wget
    state: present

- name: Install ImageMagick
  pacman:
    name: imagemagick
    state: present
