- name: install basic utils, shells, apps
  community.general.pacman:
   name:
    - linux-firmware
    - linux-headers
    - xorg
    - xorg-xinit
    - arandr
    - kitty
    - kitty-terminfo
    - vlc
    - gimp
    - git
    - thefuck
    - tmux
    - lsd
    - vim
    - source-highlight
    - tree
    - base-devel
    - gdb
    - gcc
    - cmake
    #- cmake-curses-gui
    - ccache
    - clang
    - autoconf
    - automake
    - libtool
    - htop
    #- archey3
    - patch
   state: present

- name: install ranger
  community.general.pacman:
    name:
      - python-pillow
      - python-pip
      - highlight
      - ranger

- name: Install archival utils
  pacman:
    name:
      - atool
      - p7zip
      - unrar
      - unzip
      - xz
      - zip
      - bzip2
      - gzip
      - tar
    state: present

- name: Install download utils
  pacman:
    name:
      - aria2
      - curl
      - wget
    state: present

- name: Install ImageMagick
  pacman:
    name: imagemagick
    state: present

- name: Install various extra utilities
  pacman:
    name:
      - sqlitebrowser
      - sshpass
      - repo
      - tcpdump
      - wireshark-cli
      - wireshark-qt
      - qemu-base
      - qemu-emulators-full
      - qemu-user-static
      - docker
      - docker-compose
      - code
    state: present
