- name: Clone user dotfiles
  git: repo={{ dotfiles.url }} dest=/home/{{ username }}/{{ dotfiles.destination }} accept_hostkey=yes update=no
  become: yes
  become_user: "{{ username }}"

- name: hard link the dotfiles
   shell: |
    ln -f /home/{{ username }}/{{ dotfiles.destination }}/gitconfig /home/{{ username }}/.gitconfig
    cp -ral /home/{{ username }}/{{ dotfiles.destination }}/bin /home/{{ username }}/.bin
    cp -ral /home/{{ username }}/{{ dotfiles.destination }}/config /home/{{ username }}/.config


