- name: Clone user dotfiles
  git: repo={{ dotfiles.url }} dest=/home/{{ username }}/{{ dotfiles.destination }} accept_hostkey=yes update=no
  become: yes
  become_user: "{{ username }}"

- name: Hard link the dotfiles
  shell: |
    ln -f /home/{{ username }}/{{ dotfiles.destination }}/zshrc /home/{{ username }}/.zshrc
    ln -f /home/{{ username }}/{{ dotfiles.destination }}/gitconfig /home/{{ username }}/.gitconfig
    ln -f /home/{{ username }}/{{ dotfiles.destination }}/vimrc /home/{{ username }}/.vimrc
    ln -f /home/{{ username }}/{{ dotfiles.destination }}/p10k /home/{{ username }}/.p10k
    cp -ral /home/{{ username }}/{{ dotfiles.destination }}/bin /home/{{ username }}/.bin
    cp -ral /home/{{ username }}/{{ dotfiles.destination }}/config /home/{{ username }}/.config
    cp -ral /home/{{ username }}/{{ dotfiles.destination }}/zsh /home/{{ username }}/.zsh
    cp -ral /home/{{ username }}/{{ dotfiles.destination }}/themes/ /home/{{ username }}/.themes/
    cp -ral /home/{{ username }}/{{ dotfiles.destination }}/icons/ /home/{{ username }}/.icons/

- name: link system dotfiles 
  shell: |
    mkdir -p /usr/local/share/backgrounds
    ln -s /home/{{ username }}/{{ dotfiles.destination }}/backgrounds/* /usr/local/share/backgrounds/
  become: yes
