- name: Install rendering tools
  community.general.pacman:
    name:
      - xorg
      - xorg-xinit
      - arandr

- name: Link udev rules
  shell: |
    ln -sf /home/bruno/projects/dotfiles/etc/udev/rules.d/backlight.rules /etc/udev/rules.d/backlight.rules
