- name: Install i3 
  community.general.pacman:
    name:
      - polybar
      - rofi
      - python-pywal
      - calc
      - bc
      - ttf-iosevka-nerd
      - ttf-fantasque-sans-mono
      - ttf-droid
      - compton
      - i3-gaps
      - i3blocks
      - i3lock
      - i3status
      - feh
      - scrot 
      - wmctrl
      - lxappearance
      - numlockx
      - polkit
