- name: LightDM Display manager
  community.general.pacman:
    name:
    - lightdm
    - lightdm-gtk-greeter

- name: Customize greeter
  shell: |
    mkdir -p /usr/local/share/backgrounds
    ln -f /home/{{ username }}/{{ dotfiles.destination }}/wallpapers/archlinux.jpg /usr/local/share/backgrounds/
    ln -f /home/{{ username }}/{{ dotfiles.destination }}/etc/lightdm/lightdm-gtk-greeter.conf /etc/lightdm/lightdm-gtk-greeter.conf
    ln -s /home/{{ username }}/{{ dotfiles.destination }}/themes/ /usr/local/share/themes
    ln -s /home/{{ username }}/{{ dotfiles.destination }}/icons/ /usr/local/share/icons
