- name: LightDM Display manager
  community.general.pacman:
    name:
    - lightdm
    - lightdm-gtk-greeter

- name: Customize greeter
  become: yes
  shell: |
    mkdir -p /usr/local/share/backgrounds
    ln -f /home/{{ username }}/{{ dotfiles.destination }}/backgrounds/archlinux.jpg /usr/local/share/backgrounds/
    ln -f /home/{{ username }}/{{ dotfiles.destination }}/etc/lightdm/lightdm-gtk-greeter.conf /etc/lightdm/lightdm-gtk-greeter.conf
    cp -r /home/{{ username }}/{{ dotfiles.destination }}/themes/* /usr/share/themes/
    cp -r /home/{{ username }}/{{ dotfiles.destination }}/icons/* /usr/share/icons/
