- name: check updates
  pacman: 
   update_cache: yes
   upgrade: yes


# Configure pacman (colorize and repos)
- include_tasks: pacman.yml

# Basic apps (vlc, kitty, etc.)
- include_tasks: core-apps.yml
- include_tasks: audio.yml
- include_tasks: graphics.yml
- include_tasks: networking.yml

# Install virutalbox guest utilities
- include_tasks: vbox.yml
  when: is_vm == True

# Install and configure zsh
- include_tasks: zsh.yml
  when: setup_zsh == True

# Dotfiles
- include_tasks: dotfiles.yml
  when: pull_dotfiles == True

# Install and configure spacevim
- include_tasks: spacevim.yml
  when: install_spacevim == True

# Install spacemacs
- include_tasks: spacemacs.yml
  when: install_spacemacs == True

# Install KDE and Additional Plasma Applications
- block:
    - include_tasks: kde.yml
    - include_tasks: sddm.yml
    - include_tasks: sddm_enable.yml
  when: "'1' in desktop_environment"

- block:
    - include_tasks: xfce.yml
    - include_tasks: lightdm.yml
    - include_tasks: lightdm_enable.yml
  when: "'2' in desktop_environment"

- block:
    - include_tasks: i3.yml
    - include_tasks: ly.yml
    - include_tasks: ly_enable.yml
  when: "'3' in desktop_environment" 

# Web Browser
- include_tasks: "{{browser}}.yml"

# Terminal web browsers
- include_tasks: terminal_browsers.yml
  when: install_terminal_browsers == True

# Office
- include_tasks: office.yml
  when: install_office == True

# AUR apps
- include_tasks: aur.yml
  when: use_aur == True

