- name: check updates
  pacman: 
   update_cache: yes
   upgrade: yes


# Configure pacman (colorize and repos)
- include: pacman.yml

# Basic apps (vlc, kitty, etc.)
- include: core-apps.yml

# Dotfiles
- include: dotfiles.yml
  when: pull_dotfiles == True

# Install and configure zsh
- include: zsh.yml
  when: setup_zsh == True

# Install and configure spacevim
- include: spacevim.yml
  when: install_spacevim == True

# Install spacemacs
- include: spacemacs.yml
  when: install_spacemacs == True

# Install KDE and Additional Plasma Applications
- block:
    - include: kde.yml
    - include: sddm.yml
    - include: sddm_enable.yml
  when: "'1' in desktop_environment"

- block:
    - include: xfce.yml
    - include: lightdm.yml
    - include: lightdm_enable.yml
  when: "'2' in desktop_environment"

- block:
    - include: exwm.yml
      #- include: spacemacs.yml
      #when: install_spacemacs == False
  when: "'3' in desktop_environment" 

# Web Browser
- include: "{{browser}}.yml"

# Terminal web browsers
- include: terminal_browsers.yml
  when: install_terminal_browsers == True

# Office
- include: office.yml
  when: install_office == True

# AUR apps
- include: aur.yml
  when: use_aur == True

