- name: check updates
  pacman: 
   update_cache: yes
   upgrade: yes


# Configure pacman (colorize and repos)
- include: pacman.yml

# Basic apps (vlc, kitty, etc.)
- include: core-apps.yml

# Install and configure zsh
- include: zsh.yml
  when: setup_zsh == True

# Install and configure spacevim
- include: spacevim.yml
  when: install_spacevim == True

- block:
    - include: ly.yml
    - include: ly_enable.yml
    when: display_manager == '1'

- block:
    - include: lightdm.yml
    - include: lightdm_enable.yml
    when: display_manager == '2'

- block:
    - include: sddm.yml
    - include: sddm_enable.yml
    when: display_manager == '3'


  
# Install KDE and Additional Plasma Applications
- include: kde.yml
  when: "'1' in desktop_environment"

- include: xfce.yml
  when: "'2' in desktop_environment"

# Web Browser
- include: "{{browser}}.yml"

# Terminal web browsers
- include: terminal_browsers.yml
  when: install_terminal_browsers == True

# Office
- include: office.yml
  when: install_office == True

# AUR apps
- include: aur.yml
  when: use_aur == True

# Dotfiles
- include: dotfiles.yml
  when: pull_dotfiles == True
