### Playbook Configuration Variables
# You may modify the following variables to customize the playbook to your
# specific needs, however do not remove any variables, they are all required
# for the playbook to function.

## Task Configuration
setup_zsh: True

## Dotfiles
## Please make sure to update 
pull_dotfiles: True

dotfiles:
    url: https://github.com/marques-bruno/dotfiles.git
    destination: projects/dotfiles
    rcup_flags: -fx README.md

## App Preferences
## ===========================
# Web Browser
# Value can be: vivaldi, firefox, brave, or chromium
browser: firefox

## When set to True, will install elinks and w3m
install_terminal_browsers: True

## Installs LibreOffice Fresh when True
install_office: False

## Spacevim? You know you need it
install_spacevim: False
## ===========================

## Or join the dark side
install_spacemacs: True
## ===========================

## AUR vars
## ===========================
use_aur: True

aur:
    dir: aur
    packages:
        - yay
        - downgrade
        - zplug
        - miller
        - myrepos
        - ctmg
        - spiped
        - ttf-meslo-nerd-font-powerlevel10k
        - networkmanager-dmenu
        - ttf-icomoon-feather
          #- material-icons-git
          #- ttf-material-design-icons
        - siji-ttf
## ===========================
